// <auto-generated />
namespace FMIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dde_first : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dde_first));
        
        string IMigrationMetadata.Id
        {
            get { return "202003311358389_dde_first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
