// <auto-generated />
namespace FMIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dde_third : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dde_third));
        
        string IMigrationMetadata.Id
        {
            get { return "202004010720052_dde_third"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
